language: ruby
addons:
  postgresql: "9.4"
services:
  - postgresql
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: bundle exec bin/rake spec
